server:
  port: 8089
  servlet:
    path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/day01
    username: root
    password: 0258
#    driver-class-name: com.mysql.jdbc.Driver  可以不写
#连接池
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/day01?useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化连接数
#      initial-size: 5
#      #最小空闲连接
#      min-idle: 5
#      #最大活动连接
#      maxActive: 20

#别名
mybatis:
  type-aliases-package: com.hp.pojo